### ISSUE TITLE
Is there an AIMSICDL to download?

### ISSUE THREAD

**Issue by DAMBAE** [5GSD/AIMSICDL#5]
Hi,

can anybody explain me how I can install the app AIMSICDL? I didn´t find a explanation.
Thank you!

Regards

**Comment by billotronic** [comment]
You have to compile it from source. The instructions for which can be found here: https://github.com/5GSD/AIMSICDL/wiki/Building

**Comment by rriemann** [comment]
@DAMBAE, have you tried it? What features work currently in the app?

**Comment by DAMBAE** [comment]
thx for the information. I get an new cellphone (android) in the next weeks so i can install the program. Thanks for your efforts.

**Comment by DAMBAE** [comment]
does the AIMSICDL work on Huawei P9 Lite?

**Comment by billotronic** [comment]
This should work on API 17 and newer and that phone comes with a min of 23 so you should be good.

**Comment by E3V3A** [comment]
Hi @DAMBAE 

Thanks for your interest. But...

Unless, you're planning to do some development, I simply don't see why you would want to run this. As I said in the past, AIMSICD/L are deprecated and **non working**. You can not catch anything serious with those apps. If people still think that having an IMSI-catcher detector is important, I suggest you to start help developing under the [AICDm](https://github.com/5GSD/AICDm) repo. That project has full functional clarity and clear project goals, while maintaining full android compatibility across all devices running API versions >= 23.
