### ISSUE TITLE
/dev/smd[0,7] not found

### ISSUE THREAD

**Issue by Imtiazkarimik23** [5GSD/AIMSICDL#9]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

--- HI all,

When I was looking into the code Android-IMSI-Catcher-Detector/AIMSICD/src/main/java/com/secupwn/aimsicd/ui/fragments/AtCommandFragment.java, In a comment there is written that we need to have supported hardware that already has an AT serial device
  for Qualcomm:   /dev/smd[0,7] but in Nexus 5 and Samsung Galaxy S3 I haven't been able to find /dev/smd[0-7]. I am confused about it.  I have basically two questions.
1. Does anyone have any idea on what interface Nexus 5/Galaxy S3 uses to communicate with the modem?
2. Does the RILd interface / Modem driver use the AT interface or something else to communicate for the newer android phones?

Thank you.

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

---

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

---

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

---

#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by E3V3A** [comment]
> Does anyone have any idea on what interface Nexus 5/Galaxy S3 uses to communicate with the modem?

Yes, we do, and we have known this for several years and is not relevant to this repo.
